chore: popen using utf8 encoding
KillianLucas/open-interpreter pull request #231
Opened 2023-09-10 06:40 UTC by fatelei

fix #209 using utf8 encoding instead of cp1255

2023-09-11 04:38 UTC, jordanbtucker commented
Thanks for the PR. Do you think this will also fix #93 ?

2023-09-11 05:02 UTC, fatelei commented
> Thanks for the PR. Do you think this will also fix #93 ?

i check it

2023-09-13 01:34 UTC, anewt95 approved these changes

2023-09-13 14:43 UTC, anewt95 approved these changes

2023-09-13 14:43 UTC, anewt95 commented on interpreter/code_interpreter.py
>  import os
[]()

2023-09-13 14:43 UTC, anewt95 commented on interpreter/code_interpreter.py
> +    my_env = os.environ
**[]()**

2023-09-13 14:43 UTC, anewt95 commented on interpreter/code_interpreter.py
> +    my_env = os.environ
![image](https://github.com/KillianLucas/open-interpreter/assets/143710899/0384e1a2-254d-446c-ad01-61e5c979edc5)

2023-09-14 00:37 UTC, fatelei commented
> Thanks for the PR. Do you think this will also fix #93 ?

i have reply this issue, how to resolve it, this mr only resolve subprocess popen encoding issue

2023-09-17 21:29 UTC, anewt95 approved these changes

2023-09-18 00:40 UTC, anewt95 requested changes
[]()

2023-09-18 03:07 UTC, anewt95 approved these changes

2023-10-29 13:55 UTC, ericrallen commented
Hey there, @fatelei!

Sorry we didn’t get around to this one previously.

I’d love to get this updated to work with the refactored codebase and ready to merge in.

If you want help navigating the refactor, resolving merge conflicts, etc. let me know, or if you want to start with a fresh PR and avoid the complexities of the merge conflicts with the refactor, just ping me on the new PR.

2023-11-09 05:37 UTC, fatelei commented
> Hey there, @fatelei!
> 
> Sorry we didn’t get around to this one previously.
> 
> I’d love to get this updated to work with the refactored codebase and ready to merge in.
> 
> If you want help navigating the refactor, resolving merge conflicts, etc. let me know, or if you want to start with a fresh PR and avoid the complexities of the merge conflicts with the refactor, just ping me on the new PR.

ok

2023-11-09 16:49 UTC, closed without merging

2023-11-09 16:50 UTC, fatelei commented
open a new one https://github.com/KillianLucas/open-interpreter/pull/742