return empty dict if config file is empty
KillianLucas/open-interpreter pull request #811
Opened 2023-12-03 20:15 UTC by sbendary25

### Describe the changes you have made:
`yaml.safe_load` returns `None` from the `get_config` function if the config file is empty. This change checks for `None` value and instead returns `{}` so `extend_config` call doesn't throw exception when config file is empy.

### Reference any relevant issue (Fixes #000)
https://github.com/KillianLucas/open-interpreter/issues/794

- [ ] I have performed a self-review of my code:

### I have tested the code on the following OS:
- [ ] Windows
- [ x] MacOS
- [ ] Linux

### AI Language Model (if applicable)
- [ ] GPT4
- [ ] GPT3
- [ ] Llama 7B
- [ ] Llama 13B
- [ ] Llama 34B
- [ ] Huggingface model (Please specify which one)

2023-12-05 10:18 UTC, CyanideByte requested changes
I tested the code @sbendary25 provided and it works great. I think you could go a step further and have it repair the config file using the default one. Here is some tested code below that does that.
```
def get_config(path=user_config_path):
    path = get_config_path(path)
    
    config = None

    with open(path, "r") as file:
        config = yaml.safe_load(file)
        if not config is None:
            return config

    if config is None:
        os.remove(path)
        path = get_config_path(path)
        with open(path, "r") as file:
            config = yaml.safe_load(file)
            return config
```

2023-12-06 20:23 UTC, sbendary25 commented
added @CyanideByte suggestion [a90cc8f](https://github.com/KillianLucas/open-interpreter/pull/811/commits/a90cc8fa0db14a675e2558e57cb3d63d965c7b60)

2023-12-06 21:18 UTC, Notnaton commented on interpreter/terminal_interface/utils/get_config.py
> +        if not config is None:
`if config is not None:` is better syntax
![image](https://github.com/KillianLucas/open-interpreter/assets/4324290/89555cba-f76e-4d7b-afb1-c75430ed0bd1)
from: https://pep8.org/

2023-12-06 22:46 UTC, sbendary25 commented
@Notnaton also added a message to inform user that default config is being applied

2023-12-08 21:31 UTC, sbendary25 commented
@Notnaton bumping this to be closed and merged.

2023-12-14 02:35 UTC, KillianLucas commented
Great work @sbendary25. And thanks @CyanideByte and @Notnaton for your suggestions and reviews. Merging now.

(also thanks for your comments on the latest `--os` updates Samer— you have a great attention to detail)

2023-12-14 02:35 UTC, merged